name: DESTRAL_RELEASE

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 2
        run: |
          sudo apt update
          sudo apt install python2 python-pip
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
          printf '1\n' | sudo update-alternatives --config python
          cd /usr/bin
          sudo ln -s /usr/bin/pip2 ./pip
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false
      - name: Creating a realease/pre-release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') }}
          generate_release_notes: true
      - name: Publish a Python distribution to PyPI
        if: ${{ contains(github.ref, '-rc') }} == false
        uses: conchylicultor/pypi-build-publish@v1
        with:
          pypi-token: ${{ secrets.PYPI_TOKEN }}